### ISSUE TITLE
"raw handle" and "iron rod" have the same recipe

### ISSUE THREAD

**Issue by adl** [NFINIT-Development/GalacticEngineers#10]
(Version 1.4 of the pack.)

The "raw handle" (Steve's Cart 2) and "iron rod" (libVulpes, for Advanced Rocketry) have similar recipes; attempting to craft an iron rod with 3 iron ingots gives you a raw handle instead.  JEI tells me I can also build an iron rod using a Lathe, but building a Lathe requires an iron rod, so I do not see a way to progress here.

**Comment by knoxhack** [comment]
Fixed in 1.4.0.1
