### ISSUE TITLE
Block Picked Up

### ISSUE THREAD

**Issue by HearNoMore** [NFINIT-Development/GalacticEngineers#17]
Some how I picked up my Grid (Refined Storage) and it shows in my hands as a white block and it is not in my inventory hot bar. I cannot place it back down for some reason. Every time I try to place it back where is was, Minecraft crashes and gives this error: 

The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=refinedstorage:grid, properties=[connected, direction, type]}

This is using the latest version of the modpack that is on Twitch App.

**Comment by HearNoMore** [comment]
Here is a pastebin of the crash report:

[https://pastebin.com/aZDmgYSp](https://pastebin.com/aZDmgYSp)

**Comment by carstorm** [comment]
To other admins, seems like an issue with fomfix, no?

**Comment by HearNoMore** [comment]
I think it is, I'm starting to see other modpacks with the same issues relating to foamfix on github. Althought, Foamfix claims it is not their fault. As referenced [here](https://github.com/asiekierka/FoamFix/issues/86)

**Comment by HearNoMore** [comment]
Actually, looking at the crash report, I investigated Carry On mod, and it seems to have issues with Refined Storage. I would recommend upgrading to their latest version as they have added error handling with Refined Storage mod. I will update to the latest and see if this corrects my issue.

**Comment by HearNoMore** [comment]
Updating the Carry On Mod fixed the issue.
