### ISSUE TITLE
Matter Overdrive causing CTD's on server

### ISSUE THREAD

**Issue by Tkdmaster** [NFINIT-Development/GalacticEngineers#2]
Hello, I setup a server to test this pack, and quickly found that the Matter Overdrive mod is causing a serious CTD whenever someone eats food near another player. The bug is known to the mod developer and will be fixed in the next release, but it has been nearly 2 months since his last update.

As reference, here's a link to the author's github issue on this:
https://github.com/simeonradivoev/MatterOverdrive/issues/657

So, until the next version comes out, this mod is near unplayable on a multiplayer environment sadly.

**Comment by knoxhack** [comment]
this has been fixed in version 1.2
