### ISSUE TITLE
Multi-Storage update needed.

### ISSUE THREAD

**Issue by Tkdmaster** [NFINIT-Development/GalacticEngineers#7]
Multi-storage is out of date and needs updated. the current version crashes the client whenever you open an ender-link bag, the new version fixes that.

**Comment by Nanoflight** [comment]
I don't think they really care about the modpack, I'm having issues with it, the discord link doesn't work & other stuff.

**Comment by knoxhack** [comment]
I'm out of town atm, version 1.3 will have all this fixed

**Comment by knoxhack** [comment]
Replaced by Ender Storage on version 1.3 https://minecraft.curseforge.com/projects/ender-storage-1-8
