### ISSUE TITLE
Discord link

### ISSUE THREAD

**Issue by Nanoflight** [NFINIT-Development/GalacticEngineers#8]
The discord link on the pack (on curse) isn't working, it says it's either invalid or expired.
Also I can't get on the server.

**Comment by Nanoflight** [comment]
I forgot to mention, before all the quests weren't showing up for me, they were for a few days but then just stopped.

**Comment by Nanoflight** [comment]
I'm starting to think they don't really care about this server/modpack.

**Comment by knoxhack** [comment]
I have been getting ready the new 1.3 version for a few weeks now, but my job keeps sending me out of town :( new version will have all that fixed

**Comment by Nanoflight** [comment]
Ah, i was just wondering cause i can't get on the server, and the quest book has been broken for me for a while, some other problems as well

**Comment by Nanoflight** [comment]
& the discord link doesn't work**

**Comment by Nanoflight** [comment]
I still can't get on the server on the modpack, or discord.

**Comment by carstorm** [comment]
Here is the link for the discord: https://discord.gg/zWkFGw7

**Comment by Nanoflight** [comment]
Thanks.

**Comment by knoxhack** [comment]
Im about to push an update to the pack, also the Discord link is this one: https://discord.gg/yEPWssh
